# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Mas suas capacidades vão muito além disso, como veremos nos nestes vídeos. E ele serve como uma boa base para o Pandas, que é uma das bibliotecas mais populares para análise de dados em Python.

## Arrays NumPy

Um array é uma estrutura de dados que armazena valores de um mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes.

In [2]:
import numpy as np

array = np.array([1,2,3,4,5])

print(array)

[1 2 3 4 5]


É relevante entender a diferença entre uma lista e um array.

Uma **lista** é uma das estruturas de dados mais básicas em Python. Ela pode conter qualquer tipo de elementos, como números, strings, outras listas, e todos eles podem ser de tipos diferentes. Por exemplo:


In [3]:
lista = [1, "dois", 3.0]
print(lista)

[1, 'dois', 3.0]


In [4]:
print(type(lista))

<class 'list'>


In [5]:
for elemento in lista:
    print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>


Um **array**, por outro lado, é uma estrutura de dados que também armazena elementos, mas todos os elementos devem ser do mesmo tipo. Se você tentar criar um array com elementos de tipos diferentes, o NumPy irá convertê-los todos para o tipo mais geral. Por exemplo:

In [6]:
array = np.array(lista)
print(array)

['1' 'dois' '3.0']


In [7]:
print(type(array))

<class 'numpy.ndarray'>


In [9]:
for elemento in array:
    print(type(elemento))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [10]:
print(array.dtype)

<U32



## Operações Matemáticas

Se você tentar adicionar um número a todos os elementos de uma lista, você receberá um erro.

In [11]:
lista = [1, 2, 3, 4, 5]
nova_lista = lista + 1  # Isso causará um erro
print(nova_lista)

TypeError: can only concatenate list (not "int") to list

In [12]:
nova_lista = []

for numero in lista:
    nova_lista.append(numero + 1)

print(nova_lista)

[2, 3, 4, 5, 6]


Com um array NumPy, você pode adicionar (ou subtrair, multiplicar, dividir) um número a todos os elementos de uma vez.

In [ ]:
import numpy as np

array = np.array([1,2,3,4,5])
novo_array = array + 1 # isso adicionará 1 a todos os elementos
print(novo_array)

[2 3 4 5 6]


## Desempenho

Para grandes quantidades de dados, os arrays NumPy são significativamente mais eficientes em termos de memória e desempenho do que as listas Python. Aqui está um exemplo que demonstra isso:



In [16]:
import numpy as np
import time

# Crie uma lista e um array com 10 milhões de números
lista = list(range(1, 10_000_001))
array = np.array(range(1, 10_000_001))

# Calcule a soma de todos os números na lista
inicio = time.time()
soma_lista = sum(lista)
fim = time.time()
print(f"Tempo para somar todos os números na lista: {fim - inicio} segundos")

# Calcule a soma de todos os números no array
inicio = time.time()
soma_array = np.sum(array)
fim = time.time()
print(f"Tempo para somar todos os números no array: {fim - inicio} segundos")

Tempo para somar todos os números na lista: 0.2668616771697998 segundos
Tempo para somar todos os números no array: 0.00498509407043457 segundos


## Resumindo

Aqui estão algumas diferenças chave entre listas e arrays:

1. **Tipo de dados**: As listas podem armazenar elementos de tipos diferentes ao mesmo tempo, enquanto os arrays armazenam elementos do mesmo tipo.

2. **Operações matemáticas**: Você pode realizar operações matemáticas em todos os elementos de um array de uma vez, o que não é possível com listas.

3. **Desempenho**: Arrays são mais eficientes em termos de memória e desempenho do que listas quando se trabalha com grandes quantidades de dados numéricos.

4. **Funcionalidades**: NumPy arrays vêm com várias funções integradas para operações matemáticas e científicas, como média, soma, multiplicação de matrizes, etc., que não estão disponíveis com listas.


In [7]:
import numpy as np

array = np.array(["a","b","c","d","e"])
print(array)

['a' 'b' 'c' 'd' 'e']


### Indexação e Slicing

In [8]:
print(array[0])

a


In [9]:
print(array[1:4])

['b' 'c' 'd']


In [10]:
print(array[0:-1])

['a' 'b' 'c' 'd']


In [11]:
print(array[0:-1:2])

['a' 'c']


In [12]:
print(array[0::2])

['a' 'c' 'e']


In [16]:
print(array[::])

['a' 'b' 'c' 'd' 'e']


In [14]:
print(array[::-1])

['e' 'd' 'c' 'b' 'a']


### Aplicações do dia a dia

In [1]:
import numpy as np

# Preço dos produtos
precos = np.array([20,25,30,35,40])

# Aumentar o preço em 10%
novos_precos = precos * 1.1

print(novos_precos)

[22.  27.5 33.  38.5 44. ]


### np.sum()

In [3]:
import numpy as np

vendas = np.array([200,250,300,350,280,270,450])

total_vendas = np.sum(vendas)
print(total_vendas)

2100


### np.mean()

In [4]:
import numpy as np

vendas = np.array([200,250,300,350,280,270,450])

media_vendas = np.mean(vendas)
print(media_vendas)

300.0


### np.max() e np.min()

In [5]:
import numpy as np

vendas = np.array([200,250,300,350,280,270,450])

max_vendas = np.max(vendas)
min_vendas = np.min(vendas)

print(max_vendas)
print(min_vendas)

450
200


### np.sort()

In [6]:
import numpy as np

vendas = np.array([200,250,300,350,280,270,450])

ordenado_vendas = np.sort(vendas)

print(ordenado_vendas)

[200 250 270 280 300 350 450]


### np.dot()

In [7]:
import numpy as np

quantidade = np.array([10, 20, 30, 40])

preco_unit = np.array([5, 10, 15, 20])

In [8]:
print(quantidade * preco_unit)

[ 50 200 450 800]


In [9]:
print(np.sum(quantidade * preco_unit))

1500


In [10]:
print(np.dot(quantidade,preco_unit))

1500


## Exercício 1

Você é um gerente de vendas e tem os dados de vendas de um produto para os últimos 7 dias em uma lista: `[127, 90, 201, 150, 210, 220, 115]`. Calcule a média de vendas durante a semana.

In [3]:
import numpy as np

dados = [127, 90, 201, 150, 210, 220, 115]

vendas = np.array(dados)

media_vendas = np.mean(vendas)

print(media_vendas)

159.0


## Exercício 2

Você é um analista financeiro e tem os preços de fechamento diário de uma ação para a última semana em um array NumPy: `precos = np.array([31.40, 31.25, 30.95, 31.20, 31.60, 31.50])`. Calcule o preço máximo, mínimo e a variação de preço durante a semana.

In [6]:
import numpy as np

precos = np.array([31.40, 31.25, 30.95, 31.20, 31.60, 31.50])

max_preco = np.max(precos)
min_preco = np.min(precos)
variacao = max_preco - min_preco

print(f'O máximo {max_preco}\nO mínimo {min_preco}\nA variação de {variacao:.2f}')

O máximo 31.6
O mínimo 30.95
A variação de 0.65


## Exercício 3

Sua loja vendeu em um dia 5 unidades do *Produto A*, 3 unidades do *Produto B* e 2 unidades do *Produto C*. Os preços dos produtos são, respectivamente, 100, 200 e 50 reais. Calcule o total de vendas do dia.

In [9]:
import numpy as np

quantidades = np.array([5, 3, 2])
precos = np.array([100, 200, 50])

total = np.dot(quantidades,precos)
print(f'Valor total de R$ {total:.2f}')

Valor total de R$ 1200.00


# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.


## Números aleatórios e estatística básica  

In [11]:
import numpy as np

rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [18]:
numero_aleatorio = rng.random() * 10
print(numero_aleatorio)

2.005818309437024


In [19]:
array_aleatorio = rng.random(3)
print(array_aleatorio)

[0.88496947 0.52065092 0.43035876]


 Vamos criar um cenário onde esses dados aleatórios podem ser úteis para uma análise de vendas.

Suponha que você seja um analista de vendas em uma empresa e queira entender melhor o desempenho das vendas de um produto específico. No entanto, você não tem acesso aos dados reais de vendas, então você decide gerar alguns dados de vendas aleatórios para realizar sua análise.

In [ ]:
# Gere dados de vendas falsos para 30 dias
# Vamos supor que as vendas de um produto podem variar de 50 a 200 por dia
rng = np.random.default_rng(seed=42)
dados_vendas = rng.integers(low=50, high=200, size=30)
print(dados_vendas)

Agora, você pode usar esses dados para realizar várias análises. Por exemplo, você pode querer saber qual foi o dia com as vendas mais altas, as vendas mais baixas, ou a média de vendas durante o mês. Aqui está como você pode fazer isso:

Breve resumo e conceitos simplificados das funções estatísticas citadas:

1. Mediana:
A mediana é um valor que divide um conjunto de dados em duas partes iguais. Para encontrá-la, você deve organizar os dados em ordem crescente ou decrescente e escolher o valor do meio. Se houver um número ímpar de dados, a mediana será exatamente o valor central. Se houver um número par de dados, a mediana será a média dos dois valores do meio.

2. Percentil:
O percentil é uma medida estatística que indica a posição relativa de um dado dentro de um conjunto de dados. Ele informa a porcentagem de valores que estão abaixo desse dado. Por exemplo, o percentil 50 (também conhecido como mediana) divide os dados em duas partes iguais, com 50% dos valores abaixo dele e 50% acima.

3. Desvio padrão:
O desvio padrão é uma medida que indica o quão dispersos os valores de um conjunto de dados estão em relação à média. Ele mostra a variabilidade dos dados em relação ao valor médio. Um desvio padrão maior indica que os dados estão mais espalhados, enquanto um desvio padrão menor indica que os dados estão mais próximos da média.

4. Variância:
A variância é outra medida de dispersão que indica o quão distantes os valores de um conjunto de dados estão da média. Ela é calculada como a média dos quadrados das diferenças entre cada valor e a média. A variância fornece uma medida da dispersão total dos dados, independentemente de serem maiores ou menores que a média.

Essas medidas são amplamente utilizadas na estatística para resumir e analisar conjuntos de dados. Elas fornecem informações valiosas sobre a distribuição, a variabilidade e a posição dos dados, permitindo uma compreensão mais completa dos mesmos.